'use strict';
let meta, result, revision=0;
const $=s=>document.querySelector(s);
const human=s=>s.replaceAll('_',' ');
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function inputFacts(){return Object.fromEntries([...document.querySelectorAll('[data-fact]')].map(e=>[e.dataset.fact,e.value]));}
function changed(){revision++;$('#count').textContent=Object.values(inputFacts()).filter(v=>v!=='unknown').length+' / 32 observations answered';if(result){result=null;$('#result').replaceChildren(el('p','Evidence changed. Analyze again to update the assessment.','stale'));$('#proof').replaceChildren();}}
function setFacts(f){document.querySelectorAll('[data-fact]').forEach(e=>e.value=f[e.dataset.fact]||'unknown');changed();}
function proofNode(n){const box=el('div',undefined,'proof-node');box.append(el('strong',human(n.goal)),document.createTextNode(' = '+n.value+' '),el('span',human(n.status),'status '+n.status));if(n.actual)box.append(el('div','Observation: '+n.actual));for(const a of n.alternatives||[]){const d=el('details');d.open=a.status==='proven';d.append(el('summary',a.rule+' · '+human(a.status)));for(const c of a.children)d.append(proofNode(c));box.append(d);}return box;}
function render(r){
 const out=$('#result');out.replaceChildren();const p=el('div',undefined,'priority '+r.priority);p.append(el('small','PROJECT TRIAGE PRIORITY'),el('b',r.priority),el('span',r.categories.length?'Suspected incident indicators detected':'Insufficient rule support; continue investigation'));out.append(p);
 const chips=el('div',undefined,'chips');r.categories.forEach(c=>chips.append(el('span',human(c),'chip')));out.append(chips,el('h3','Recommended next steps'));
 const list=el('ol',undefined,'actions');r.actions.forEach(a=>list.append(el('li',a.text)));if(!r.actions.length)list.append(el('li','Gather more evidence and ask an analyst to review the event.'));out.append(list);
 const trace=el('details');trace.append(el('summary','Forward chaining trace · '+r.trace.length+' rules fired'));
 for(const t of r.trace){const row=el('div',undefined,'trace-entry');row.append(el('strong','Round '+t.round+' · '+t.rule),el('p',t.conditions.map(c=>human(c.fact)+' = '+c.value).join(' AND ')),el('code','THEREFORE '+human(t.conclusion)),el('p',t.explanation),el('small','References: '+t.sources.join(', ')));trace.append(row);}out.append(trace,el('p',r.notice,'notice'));
 const exportButton=el('button','Export case and reasoning','secondary export');exportButton.onclick=()=>{const blob=new Blob([JSON.stringify({...r,exported_at:new Date().toISOString()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=el('a');a.href=url;a.download='cyber-triage-case.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};out.append(exportButton);
 $('#proof').replaceChildren(proofNode(r.proof));if(r.questions.length){const x=el('div');x.append(el('h3','Evidence to collect for this goal'));const ul=el('ul',undefined,'actions');r.questions.forEach(q=>ul.append(el('li',meta.kb.facts.find(f=>f.id===q).label)));x.append(ul);$('#proof').append(x);}
}
async function run(){const at=revision;$('#error').textContent='';$('#analyze').disabled=$('#prove').disabled=true;try{const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({facts:inputFacts(),goal:$('#goal').value})});const data=await response.json();if(!response.ok)throw Error(data.error||'Analysis failed');if(at!==revision){$('#error').textContent='Inputs changed during analysis. Please analyze again.';return;}result=data;render(data);}catch(e){$('#error').textContent=e.message;}finally{$('#analyze').disabled=$('#prove').disabled=false;}}
function renderRules(){const term=$('#search').value.toLowerCase();$('#rules').replaceChildren();meta.kb.rules.filter(r=>JSON.stringify(r).toLowerCase().includes(term)).forEach(r=>{const row=el('div',undefined,'rule');row.append(el('strong',r.id+' · '+human(r.conclusion)),el('p','IF '+r.conditions.map(c=>human(c.fact)+' = '+c.value).join(' AND ')),el('code','THEN '+human(r.conclusion)),el('p',r.explanation),el('small',r.kind+' · References '+r.sources.join(', ')));$('#rules').append(row);});}
async function init(){try{const response=await fetch('/api/meta');if(!response.ok)throw Error('Unable to load the knowledge base');meta=await response.json();$('#engine').textContent=meta.engine;
 const groups=[...new Set(meta.kb.facts.map(f=>f.group))];groups.forEach((g,i)=>{const d=el('details');d.open=i===0;d.append(el('summary',g+' · '+meta.kb.facts.filter(f=>f.group===g).length+' observations'));meta.kb.facts.filter(f=>f.group===g).forEach(f=>{const row=el('div',undefined,'question'),label=el('label',f.label);label.htmlFor=f.id;label.append(el('small',f.help));const select=el('select');select.id=f.id;select.dataset.fact=f.id;['unknown','yes','no'].forEach(v=>{const o=el('option',v[0].toUpperCase()+v.slice(1));o.value=v;select.append(o);});select.onchange=changed;row.append(label,select);d.append(row);});$('#questions').append(d);});
 meta.scenarios.forEach((s,i)=>{const o=el('option',s.name);o.value=String(i);$('#scenario').append(o);});
 [...meta.kb.categories,'priority_critical','action_isolate'].forEach(g=>{const o=el('option',human(g));o.value=g;$('#goal').append(o);});$('#goal').value='ransomware';
 $('#scenario').onchange=()=>{setFacts($('#scenario').value===''?{}:meta.scenarios[Number($('#scenario').value)].facts);document.querySelectorAll('#questions details').forEach(d=>d.open=true);};
 $('#reset').onclick=()=>{$('#scenario').value='';setFacts({});$('#error').textContent='';};$('#goal').onchange=()=>{revision++;$('#proof').replaceChildren(el('p','Goal changed. Check the hypothesis again.','stale'));};$('#analyze').onclick=$('#prove').onclick=run;
 document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==b.dataset.tab));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));});
 $('#search').oninput=renderRules;renderRules();meta.kb.sources.forEach(s=>{const d=el('div',undefined,'source');d.append(el('strong',s.id+' · '+s.title+' ('+s.year+')'),el('p',s.scope));if(s.url){const a=el('a',s.url);a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';d.append(a);}$('#sources').append(d);});
 }catch(e){$('#engine').textContent='Engine unavailable';$('#error').textContent=e.message+'; start server.py and reload.';}}
init();
